version: '3.9'

services:
  api:
    build: .
    container_name: homeclub-api
    ports:
      - '3000:3000'
    depends_on:
      db1:
        condition: service_healthy
      db2:
        condition: service_healthy
    environment:
      DATABASE_URL_DB1: mysql://root:root@db1:3306/homeclub_db1
      DATABASE_URL_DB2: mysql://root:root@db2:3306/homeclub_db2
    command: npm run start:dev
    restart: on-failure

  db1:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homeclub_db1
    volumes:
      - ./docker/sql/db1-init.sql:/docker-entrypoint-initdb.d/init.sql
      - db1_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
  db2:
    image: mysql:8
    ports:
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: homeclub_db2
    volumes:
      - ./docker/sql/db2-init.sql:/docker-entrypoint-initdb.d/init.sql
      - db2_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  db1_data:
  db2_data:
